name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <-- this grants GITHUB_TOKEN push access

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run build

      - name: Configure base path for Vite
        run: |
          echo "Adding base path to index.html"
          sed -i 's|<script type="module" src="/src/main.tsx"></script>|<script type="module" src="./src/main.tsx"></script>|g' dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # ensure you're deploying to gh-pages branch
